name: myfuwu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
